wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1676782855.309153
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 16
      - 17
      - 23
      - 37
      4: 3.9.12
      5: 0.13.10
      8:
      - 3
      - 8
architecture:
  desc: null
  value: MF
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.05
